export const SET_DATA = 'SET_DATA';

export const SECTION_CHANGE_TITLE = 'SECTION_CHANGE_TITLE';
export const SECTION_DELETE = 'SECTION_DELETE';
export const SECTION_CREATE = 'SECTION_CREATE';

export const SCENARIO_CREATE = 'SCENARIO_CREATE';
export const SCENARIO_DELETE = 'SCENARIO_DELETE';
export const SCENARIO_MODIFY = 'SCENARIO_MODIFY';

export const TABLE_CREATE = 'TABLE_CREATE';
export const TABLE_DELETE = 'TABLE_DELETE';
export const TABLE_MODIFY = 'TABLE_MODIFY';
